### ISSUE TITLE
Review 1: Penggunaan kode buku

### ISSUE THREAD

**Issue by priyandari** [ghanint/kelompok-6#3]
Sebaiknya buku diberi kode tertentu agar saat mau pinjam buku atau kembalikan buku, pengguna program tidak harus menuliskan judul buku yang kemungkinan panjang.. apalagi saat setelah memilih menu 2, tidak ditampilkan daftar buku

**Comment by ghanint** [comment]
issue ini sudah kami benahi ya pak, sehingga saat pemilihan buku tidak perlu menulis judul buku terlalu panjang, daftar buku juga akan terlihat
