### ISSUE TITLE
Review 1: Jumlah buku jika lebih dari 1 ?

### ISSUE THREAD

**Issue by priyandari** [ghanint/kelompok-6#4]
Bagaimana jika jumlah **sebuah judul** buku lebih dari 1 ? bagaiamana tahu bahwa buku masih dipinjam ?

**Comment by priyandari** [comment]
Ini solusinya bagaimana ?
Buku No 1 hanya ada 1 buah
Buku No 2 ada dua buah.

Buku No 1 dipinjam Budi dan belum dikembalikan. Harusnya tidak boleh tiba2 dipinjam ke Agung

Jadi ada informasi stok atau persediaan buku di perpus ada berapa

**Comment by ghanint** [comment]
feature untuk stock sudah kami tambahkan, jadi akan ada keterangan stock. saat dipinjamkan stock juga akan berkurang, lalu saat pengembalian, stock akan bertambah kembali
