### ISSUE TITLE
Review 1: Error karena salah input ..

### ISSUE THREAD

**Issue by priyandari** [ghanint/kelompok-6#5]
======================================================================================
|  Selamat datang di Perpustakaan HMTI. Silahkan pilih menu untuk melanjutkan        |
|  1. Tampilkan buku                                                                 |
|  2. Pinjamkan buku                                                                 |
|  3. Tambahkan buku                                                                 |
|  4. Kembalikan buku                                                                |
======================================================================================
Input = 1
Berikut merupakan daftar buku yang dimiliki Perpustakaan HMTI
Al-Quran
Al-kitab
Weda
Tripitaka
Shishu Wujing

Tekan K untuk keluar dan L untuk lanjut
3
l
L
======================================================================================
|  Selamat datang di Perpustakaan HMTI. Silahkan pilih menu untuk melanjutkan        |
|  1. Tampilkan buku                                                                 |
|  2. Pinjamkan buku                                                                 |
|  3. Tambahkan buku                                                                 |
|  4. Kembalikan buku                                                                |
======================================================================================
Input = 3
Masukkan judul buku yang ingin ditambahkan 
Input = Kungfu Boy
buku telah ditambahkan ke dalam list

Tekan K untuk keluar dan L untuk lanjut
L
======================================================================================
|  Selamat datang di Perpustakaan HMTI. Silahkan pilih menu untuk melanjutkan        |
|  1. Tampilkan buku                                                                 |
|  2. Pinjamkan buku                                                                 |
|  3. Tambahkan buku                                                                 |
|  4. Kembalikan buku                                                                |
======================================================================================
Input = 1
Berikut merupakan daftar buku yang dimiliki Perpustakaan HMTI
Al-Quran
Al-kitab
Weda
Tripitaka
Shishu Wujing
Kungfu Boy

Tekan K untuk keluar dan L untuk lanjut
L
======================================================================================
|  Selamat datang di Perpustakaan HMTI. Silahkan pilih menu untuk melanjutkan        |
|  1. Tampilkan buku                                                                 |
|  2. Pinjamkan buku                                                                 |
|  3. Tambahkan buku                                                                 |
|  4. Kembalikan buku                                                                |
======================================================================================
Input = 2
Masukkan judul buku yang ingin dipinjamkan 
Input = shis
Masukkan nama peminjam 
Input = Yusuf
Perpustakaan HMTI telah berhasil merekam peminjaman

Tekan K untuk keluar dan L untuk lanjut
L
======================================================================================
|  Selamat datang di Perpustakaan HMTI. Silahkan pilih menu untuk melanjutkan        |
|  1. Tampilkan buku                                                                 |
|  2. Pinjamkan buku                                                                 |
|  3. Tambahkan buku                                                                 |
|  4. Kembalikan buku                                                                |
======================================================================================
Input = 1
Berikut merupakan daftar buku yang dimiliki Perpustakaan HMTI
Al-Quran
Al-kitab
Weda
Tripitaka
Shishu Wujing
Kungfu Boy

Tekan K untuk keluar dan L untuk lanjut
4
L
======================================================================================
|  Selamat datang di Perpustakaan HMTI. Silahkan pilih menu untuk melanjutkan        |
|  1. Tampilkan buku                                                                 |
|  2. Pinjamkan buku                                                                 |
|  3. Tambahkan buku                                                                 |
|  4. Kembalikan buku                                                                |
======================================================================================
Input = 4
Masukkan judul buku yang ingin dikembalikan 
Input = kungfu boy
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-eb6b501b3e11> in <module>()
     57         elif user_choice == 4:
     58             buku = input("Masukkan judul buku yang ingin dikembalikan \nInput = ")
---> 59             hmti.KembalikanBuku(buku)
     60 
     61         else:

<ipython-input-1-eb6b501b3e11> in KembalikanBuku(self, buku)
     22 
     23     def KembalikanBuku(self, buku):
---> 24         self.BukuTerpinjam.pop(buku)
     25 
     26 if __name__ == '__main__':

KeyError: 'kungfu boy'

**Comment by priyandari** [comment]
Perhatikan luaran program yang saya coba itu

**Comment by ghanint** [comment]
sudah kami benahi dengan pemberian indeks nomor saat penginputan, jadi tidak perlu mengisi dengan judul buku yang terlalu panjang dan tidak simpel. terima kasih
