### ISSUE TITLE
Review 1: Sebaiknya data tersimpan dalam file xlsx atau csv

### ISSUE THREAD

**Issue by priyandari** [ghanint/kelompok-6#6]
Sebaiknya data buku tersimpan dalam file xlsx atau csv
Sebaiknya data peminjaman tersimpan dalam file xlsx atau csv
saat pinjam simpan juga tanggal pinjam

**Comment by ghanint** [comment]
sebelumnya mohon maaf pak, jadi revisi pertama sebenarnya sudah menggunakan csv namun permasalahan issue perihal stock belum menemukan caranya, jadinya kami menggunakan txt untuk penyimpanan data buku nya
